useFixture(default)

def test():
    java_recorded_version = '1.6.0_22'

# start the server start mentenance , stop mentennce , stop mentenance
    if window('Server GUI'):
        select('FormattedTextField', '127.000.000.001')
        select('FormattedTextField1', '11111')
        select('TextField', r'C:\Users\vll\vlad\scoala\test')
        assert_p('Label5', 'Text', 'OK')
        assert_p('FormattedTextField', 'Enabled', 'true')
        assert_p('FormattedTextField', 'Text', '127.000.000.001')
        assert_p('FormattedTextField1', 'Enabled', 'true')
        assert_p('Label1', 'Text', 'Stopped')
        assert_p('Start Server', 'Text', 'Start Server')
        assert_p('Start Server', 'Enabled', 'true')
        click('Start Server')
        assert_p('Label1', 'Text', 'Started')
        assert_p('FormattedTextField', 'Enabled', 'false')
        assert_p('FormattedTextField1', 'Enabled', 'false')
        assert_p('Browse', 'Enabled', 'false')
        assert_p('TextField', 'Enabled', 'false')
        assert_p('Start Server', 'Text', 'Stop Server')
        assert_p('Start Server', 'Text', 'Stop Server')
        assert_p('Label1', 'Text', 'Started')
        assert_p('Start Mentenance', 'Text', 'Start Mentenance')
        click('Start Mentenance')

        if window('Message'):
            assert_p('OK', 'Text', 'OK')
            click('OK')
        close()

        select('TextField1', r'C:\Users\vll\vlad\scoala\test')
        assert_p('Label7', 'Text', 'OK')
        assert_p('Start Mentenance', 'Text', 'Start Mentenance')
        click('MetalTitlePane', 89, 8)
        click('MetalTitlePane', 262, 14)
        click('MetalTitlePane', 150, 15)
        click('Start Mentenance')
        assert_p('FormattedTextField', 'Enabled', 'false')
        assert_p('FormattedTextField1', 'Enabled', 'false')
        assert_p('Stop Server', 'Enabled', 'false')
        assert_p('Label1', 'Text', 'Mentenace')
        assert_p('Browse1', 'Enabled', 'false')
        assert_p('TextField1', 'Enabled', 'false')
        assert_p('TextField', 'Enabled', 'true')
        assert_p('Browse', 'Enabled', 'true')
        assert_p('Start Mentenance', 'Text', 'Stop Mentenace')
        click('Start Mentenance')
        assert_p('Start Mentenance', 'Enabled', 'true')
        assert_p('Start Mentenance', 'Text', 'Start Mentenance')
        assert_p('Label1', 'Text', 'Started')
        assert_p('TextField1', 'Enabled', 'true')
        assert_p('Browse1', 'Enabled', 'true')
        click('MetalTitlePane', 241, 13)
        click('MetalTitlePane', 130, 12)
        click('Stop Server')
        assert_p('FormattedTextField', 'Enabled', 'true')
        assert_p('FormattedTextField1', 'Enabled', 'true')
        assert_p('Label1', 'Text', 'Stopped')
        assert_p('TextField', 'Enabled', 'true')
        assert_p('TextField1', 'Enabled', 'true')
        assert_p('Browse1', 'Enabled', 'true')
        assert_p('Browse', 'Enabled', 'true')
        assert_p('Start Mentenance', 'Enabled', 'true')
        assert_p('Start Mentenance', 'Text', 'Start Mentenance')
   

    close()
